project:
  type: website
  resources:
    - "assets/"

website:
  title: "Alexandre Gosset"
  navbar:
    left:
      - text: "🇫🇷 Français"
        menu:
          - text: "Accueil"
            href: index.qmd
          - text: "Projets"
            href: projects.qmd
      - text: "🇬🇧 English"
        menu:
          - text: "Home"
            href: en/index.qmd
          - text: "Projects"
            href: en/projects.qmd
    right:
      - icon: github
        href: https://github.com/AlexandreGoss
      - icon: linkedin
        href: https://www.linkedin.com/in/alexandre-gosset-22b02024b/

format:
  html:
    theme:
      light: cosmo
      dark: darkly 
    css: styles.css
    toc: true