project:
  type: website
  resources:
    - "assets/"

website:
  title: "Alexandre Gosset"
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Projets & Portfolio"
        href: projects.qmd
    right:
      - text: "🇬🇧 English"
        menu:
          - text: "Home"
            href: en/index.qmd
          - text: "Projects"
            href: en/projects.qmd
      - icon: github
        href: https://github.com/AlexandreGoss
      - icon: linkedin
        href: https://www.linkedin.com/in/alexandre-gosset-22b02024b/

format:
  html:
    theme:
      light: cosmo
      dark: darkly 
    css: styles.css
    toc: true