project:
  type: website

website:
  title: "Alexandre Gosset"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: projects.qmd
        text: Projets
    right:
      - icon: github
        href: https://github.com/AlexandreGoss
      - icon: linkedin
        href: https://www.linkedin.com/in/alexandre-gosset-22b02024b/

format:
  html:
    theme:
      light: cosmo      # Un thème clair, très propre et pro
      dark: darkly      # Le mode sombre qui s'activera automatiquement
    css: styles.css
    toc: true           # Ajoute un sommaire sur le côté pour les longs articles